version: '3.8'

services:
  my-go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    environment:
      - PORT=8080  
      - ADMIN_USERNAME=adminTax
      - ADMIN_PASSWORD=admin!
      - postgres

  postgres:
    image: postgres:12.12
    environment:
      POSTGRES_DB: Assessment-Tax
      POSTGRES_USER: mhxzvtem
      POSTGRES_PASSWORD: Fu3zMMOsZuiRERnb5s7gPcEHwMxukDDV
      DATABASE_URL: postgres://mhxzvtem:Fu3zMMOsZuiRERnb5s7gPcEHwMxukDDV@rain.db.elephantsql.com
    ports:
      - "5432:5432"
